/**
 * This code was generated by Builder.io
 */
import React from "react";
import styled from "styled-components";
import { MatchData } from "./types";

const MatchCard: React.FC<MatchData> = ({
  name,
  avatar,
  matchPercentage,
  skills,
  description,
}) => {
  return (
    <Card>
      <CardHeader>
        <ProfileInfo>
          <Avatar src={avatar} alt={`${name}'s avatar`} />
          <Name>{name}</Name>
        </ProfileInfo>
        <MatchPercentage>{matchPercentage}%</MatchPercentage>
      </CardHeader>
      <SkillsContainer>
        {skills.map((skill, index) => (
          <Skill key={index}>{skill}</Skill>
        ))}
        {skills.length > 3 && <MoreSkills>+{skills.length - 3}</MoreSkills>}
      </SkillsContainer>
      <Description>
        {description}
        <ExpandIcon
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/0b4c29b93a65fc4cdd1c745e6045e985bf7e7790e09c70538fdb4a1f0ba8d0ca?placeholderIfAbsent=true&apiKey=3d2732e2da6e4ff0afc195a1cfed46f7"
          alt="Expand"
        />
      </Description>
    </Card>
  );
};

const Card = styled.article`
  border-radius: 8px;
  background-color: #fff;
  box-shadow: 0 3px 15px rgba(189, 189, 189, 0.1);
  display: flex;
  margin-top: 16px;
  min-height: 227px;
  width: 313px;
  max-width: 100%;
  flex-direction: column;
  justify-content: center;
  padding: 14px 14px 14px 16px;
`;

const CardHeader = styled.header`
  display: flex;
  width: 100%;
  gap: 20px;
  font-family: Syne, sans-serif;
  text-align: center;
  justify-content: space-between;
`;

const ProfileInfo = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
`;

const Avatar = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 48px;
  border-radius: 50%;
`;

const Name = styled.h3`
  color: #000;
  font-size: 24px;
  font-weight: 600;
`;

const MatchPercentage = styled.span`
  color: #0d062d;
  font-size: 16px;
  font-weight: 585;
  margin: auto 0;
`;

const SkillsContainer = styled.div`
  display: flex;
  margin-top: 19px;
  align-items: center;
  gap: 8px;
  font-size: 16px;
  color: #0d062d;
  font-weight: 400;
  white-space: nowrap;
  text-align: center;
  justify-content: flex-start;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const Skill = styled.span`
  border-radius: 32px;
  background-color: rgba(59, 114, 233, 0.1);
  padding: 4px 8px;
  border: 2px solid #3b72e9;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const MoreSkills = styled.span`
  color: #000;
`;

const Description = styled.p`
  display: flex;
  margin-top: 16px;
  flex-direction: column;
  font-size: 16px;
  color: #0d062d;
  font-weight: 400;
`;

const ExpandIcon = styled.img`
  aspect-ratio: 1;
  object-fit: contain;
  object-position: center;
  width: 24px;
  align-self: center;
  margin-top: 8px;
`;

export default MatchCard;
