/**
 * This code was generated by Builder.io
 */
import React from "react";
import styled from "styled-components";
import Header from "./Header";
// import Sidebar from "./Sidebar";
import ProjectList from "./ProjectList";

interface DashboardProps {}

const Dashboard: React.FC<DashboardProps> = () => {
  return (
    <DashboardContainer>
      <Header />
      <MainContent>
        {/* <Sidebar /> */}
        <ProjectList />
      </MainContent>
    </DashboardContainer>
  );
};

const DashboardContainer = styled.div`
  background-color: #fff;
  display: flex;
  width: 30vh;
  flex-direction: column;
  flex-grow: 1;
  padding: 32px 0 368px;
  @media (max-width: 991px) {
    padding-bottom: 100px;
  }
`;

const MainContent = styled.main`
  display: grid;
  margin-top: 32px;
  width: 100%;
  padding: 0 20px;
`;

export default Dashboard;
