/**
 * This code was generated by Builder.io
 */
import React from "react";
import styled from "styled-components";

interface ProjectProps {
  name: string;
  color: string;
}

const Project: React.FC<ProjectProps> = ({ name, color }) => (
  <ProjectItem>
    <ProjectStatus color={color} />
    <ProjectName>{name}</ProjectName>
  </ProjectItem>
);

const ProjectList: React.FC = () => {
  const projects: ProjectProps[] = [
    { name: "MedHealth", color: "rgba(112, 209, 192, 1)" },
    { name: "Intel Redesign", color: "rgba(255, 165, 0, 1)" },
    { name: "Design System", color: "rgba(239, 138, 143, 1)" },
    { name: "Wireframes", color: "rgba(106, 116, 213, 1)" },
  ];

  return (
    <ProjectListContainer>
      <ProjectListHeader>
        <ProjectListTitle>my projects</ProjectListTitle>
        <AddProjectIcon
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/2c33f432abb12156e14161407baa66bbccf5994d835651f0345d9eabf75ab8e8?placeholderIfAbsent=true&apiKey=3d2732e2da6e4ff0afc195a1cfed46f7"
          alt="Add project"
        />
      </ProjectListHeader>
      {projects.map((project, index) => (
        <Project key={index} {...project} />
      ))}
    </ProjectListContainer>
  );
};

const ProjectListContainer = styled.section`
  flex-grow: 1;
`;

const ProjectListHeader = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 22px;
`;

const ProjectListTitle = styled.h2`
  font-size: 12px;
  font-weight: 600;
  text-transform: uppercase;
  margin: 0;
`;

const AddProjectIcon = styled.img`
  width: 24px;
  height: 24px;
  object-fit: contain;
  cursor: pointer;
`;

const ProjectItem = styled.div`
  display: flex;
  align-items: center;
  gap: 16px;
  margin-bottom: 30px;
`;

const ProjectStatus = styled.div<{ color: string }>`
  background-color: ${(props) => props.color};
  border-radius: 50%;
  width: 9px;
  height: 8px;
`;

const ProjectName = styled.span`
  font-family: Inter, sans-serif;
  font-size: 16px;
  font-weight: 500;
`;

export default ProjectList;
